# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishedDate',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 4, 8, 19, 30, 18, 672102), null=True),
        ),
    ]
